---
- name: Clone web-rust-api repository and execute docker-compose
  hosts: all
  become: true
  vars:
    repository_url: "https://github.com/FabioArias0/web-rust-api"
  tasks:
    - name: Check if git is installed
      ansible.builtin.command: git --version
      register: git_check
      ignore_errors: yes

    - name: Install git if not installed
      ansible.builtin.package:
        name: git
        state: present
      when: git_check.rc != 0

    - name: Install dependencies on Debian
      ansible.builtin.command: apt-get update
  

    - name: Install additional packages on Debian
      ansible.builtin.package:
        name: apt-transport-https, ca-certificates, curl, gnupg-agent, software-properties-common
        state: present
  
        
    - name: Add Docker APT key
      ansible.builtin.command: curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -
      when: ansible_os_family == 'Debian'
      

    - name: Add Docker APT repository
      ansible.builtin.command: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"
      when: ansible_os_family == 'Debian'

  
    - name: Install Docker CE on Debian
      ansible.builtin.package: 
        name: docker-ce docker-ce-cli containerd.io
        state: present
      when: ansible_os_family == 'Debian'


    - name: Check if web-rust-api repository is already cloned
      ansible.builtin.stat:
        path: /path/to/web-rust-api
      register: repo_stat
    

    - name: Clone web-rust-api repository if not already cloned
      ansible.builtin.git:
        repo: https://github.com/FabioArias0/web-rust-api
        dest: /path/to/web-rust-api
              version: master
      when: repo_stat.stat.isdir == False


    - name: Add Docker APT key on Debian
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/debian/gpg
        dest: /tmp/docker_gpg_key
      when: ansible_distribution == 'Debian'

    - name: Add Docker APT key on Ubuntu
       ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /tmp/docker_gpg_key
      when: ansible_distribution == 'Ubuntu'
 

    - name: Execute docker-compose
      ansible.builtin.command: docker-compose up -d
      args:
        chdir: /path/to/clone/web-rust-api

    - name: Commit changes to main branch
      ansible.builtin.git:
        repo: /path/to/clone/web-rust-api
        msg: "Successfully connected and executed the app on {{ ansible_hostname }}."
        push: yes
        push_to: origin
        remote: origin
        branch: master
