---
- name: Install Docker and Docker Compose
  hosts: all
  tasks:
    - name: Check if Docker is installed - Debian
      ansible.builtin.command: "dpkg -l | grep -E '^ii' | grep -E 'docker-ce|docker-ce-cli|containerd.io'"
      register: docker_installed
      changed_when: false
      become: true
      when: ansible_os_family == 'Debian'

    - name: Install prerequisites - Debian
      ansible.builtin.package:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
      become: true
      when: ansible_os_family == 'Debian' and docker_installed.rc != 0

    - name: Add Docker APT key - Debian
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/debian/gpg
      become: true
      when: ansible_os_family == 'Debian' and docker_installed.rc != 0

    - name: Add Docker APT repository - Debian
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_distribution_release|lower }} stable
        state: present
      become: true
      when: ansible_os_family == 'Debian' and docker_installed.rc != 0

    - name: Update apt and install Docker CE, Docker CLI, containerd.io - Debian
      ansible.builtin.package:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
      become: true
      when: ansible_os_family == 'Debian' and docker_installed.rc != 0

    - name: Install Docker Buildx Plugin - Debian
      ansible.builtin.command: >
        docker buildx install
      become: true
      when: ansible_os_family == 'Debian' and docker_installed.rc != 0

    - name: Install Docker Compose - Debian and Ubuntu
      ansible.builtin.get_url:
        url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '0755'
      become: true
      when: (ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian') and docker_installed.rc != 0

    - name: Start and enable Docker service - Debian
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes
      become: true
      when: ansible_os_family == 'Debian' and docker_installed.rc != 0

    - name: Check if Docker is installed - Fedora
      ansible.builtin.command: "rpm -q docker-ce docker-ce-cli containerd.io"
      register: docker_installed
      changed_when: false
      become: true
      when: ansible_os_family == 'RedHat'

    - name: Install prerequisites - Fedora
      ansible.builtin.package:
        name:
          - dnf-plugins-core
          - curl
          - policycoreutils-python-utils
      become: true
      when: ansible_os_family == 'RedHat' and docker_installed.rc != 0

    - name: Add Docker YUM repository - Fedora
      ansible.builtin.yum_repository:
        name: Docker
        description: Docker Repository
        baseurl: https://download.docker.com/linux/fedora/32/x86_64/stable
        gpgcheck: yes
        gpgkey: https://download.docker.com/linux/fedora/gpg
      become: true
      when: ansible_os_family == 'RedHat' and docker_installed.rc != 0

    - name: Install Docker CE - Fedora
      ansible.builtin.package:
        name: docker-ce
        state: latest
      become: true
      when: ansible_os_family == 'RedHat' and docker_installed.rc != 0

    - name: Install Docker Compose - Fedora
      ansible.builtin.get_url:
        url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '0755'
      become: true
      when: ansible_os_family == 'RedHat' and docker_installed.rc != 0

    - name: Start and enable Docker service - Fedora
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes
      become: true
      when: ansible_os_family == 'RedHat' and docker_installed.rc != 0
